services:
  - type: web
    name: chatgenius-backend
    env: node
    buildCommand: cd backend && npm install && npx prisma generate && npm run build
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
      - key: CLERK_SECRET_KEY
        sync: false
      - key: FRONTEND_URL
        sync: false

  - type: web
    name: chatgenius-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        value: https://chatgenius-backend.onrender.com
      - key: VITE_WS_URL
        value: wss://chatgenius-backend.onrender.com
      - key: VITE_CLERK_PUBLISHABLE_KEY
        sync: false
      - key: VITE_CLERK_PROXY_URL
        value: https://accounts.clerk.services 