services:
  - type: web
    name: chatgenius-assistant
    env: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt --no-cache-dir
    startCommand: prisma-client-py generate && bash start.sh
    envVars:
      - key: ASSISTANT_PORT
        value: 8000
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: MODEL_NAME
        value: gpt-4-1106-preview
      - key: BACKEND_URL
        value: https://chatgenius-backend.onrender.com
      - key: FRONTEND_URL
        value: https://chatgenius.fyi
      - key: LANGCHAIN_API_KEY
        sync: false
      - key: LANGCHAIN_TRACING_V2
        value: "true"
      - key: LANGCHAIN_PROJECT
        value: "chatgenius"
      - key: ASSISTANT_BOT_USER_ID
        value: "assistant-bot"

  - type: web
    name: chatgenius-backend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npx prisma generate && npm start
    envVars:
      - key: BACKEND_PORT
        value: 5000
      - key: NODE_ENV
        value: production
      - key: ASSISTANT_SERVICE_URL
        value: https://chatgenius-assistant.onrender.com
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_PHONE_NUMBER
        sync: false
      - key: FRONTEND_URL
        value: https://chatgenius.fyi
      - key: LANGCHAIN_API_KEY
        sync: false
      - key: LANGCHAIN_TRACING_V2
        value: "true"
      - key: LANGCHAIN_PROJECT
        value: "chatgenius"

  - type: web
    name: chatgenius-frontend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run serve
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        value: https://chatgeniusmvp-backend.onrender.com
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_PHONE_NUMBER
        sync: false
      - key: FRONTEND_URL
        value: https://chatgeniusmvp-frontend.onrender.com
      - key: LANGCHAIN_API_KEY
        sync: false
      - key: LANGCHAIN_TRACING_V2
        value: "true"
      - key: LANGCHAIN_PROJECT
        value: "chatgenius"

  - type: cron
    name: restart-assistant
    schedule: "0 */4 * * *"
    command: curl -X POST https://api.render.com/v1/services/$ASSISTANT_SERVICE_ID/restart -H "Authorization: Bearer $RENDER_API_KEY"
    envVars:
      - key: RENDER_API_KEY
        sync: false
      - key: ASSISTANT_SERVICE_ID
        sync: false

  - type: cron
    name: restart-backend
    schedule: "0 */4 * * *"
    command: curl -X POST https://api.render.com/v1/services/$BACKEND_SERVICE_ID/restart -H "Authorization: Bearer $RENDER_API_KEY"
    envVars:
      - key: RENDER_API_KEY
        sync: false
      - key: BACKEND_SERVICE_ID
        sync: false 